blank_issues_enabled: false
contact_links:
  - name: Confidential Issues and Bugs
    url: https://warpdotdev.typeform.com/to/jaqfsdnz
    about: Submit any confidential bugs or issues to the Warp support team.
  - name: Warp Issue Search
    url: https://github.com/warpdotdev/warp/issues?q=is%3Aissue+is%3Aopen+a+sort%3Areactions-%2B1-desc
    about: Search Warp's open issues and feature requests.
  - name: Warp Documentation
    url: https://docs.warp.dev/help/known-issues?q=
    about: Documentation for known issues, troubleshooting, keyboard shortcuts, features, telemetry table, and more!
  - name: Warp Community Search
    url: https://widget.orbit.love/widget/55808c32-c958-4da7-83de-3512fea1b278
    about: Search Warp's community for solutions to common issues.
  - name: Warp Discord
    url: https://discord.gg/warpdotdev
    about: Discuss what you want to see in a modern terminal, report bugs, and brainstorm features for Warp.
  - name: Warp Homepage
    url: https://www.warp.dev/
    about: Homepage for all things Warp.
  - name: Warp Blog
    url: https://blog.warp.dev/
    about: See our blog posts about engineering, product, and company updates.
  - name: Warp Changelog
    url: https://docs.warp.dev/help/changelog
    about: See our changelog to learn about new features, improvements, and bug fixes.
  - name: Warp Licenses
    url: https://docs.warp.dev/help/licenses
    about: See the open source projects Warp depends on and their licenses.
