blank_issues_enabled: false
contact_links:
  - name: Warp Issue Search
    url: https://github.com/warpdotdev/warp/issues?q=is%3Aissue+is%3Aopen+a+sort%3Areactions-%2B1-desc
    about: Search Warp's open issues and feature requests.
  - name: Confidential Issues and Bugs
    url: https://warpdotdev.typeform.com/to/jaqfsdnz
    about: Submit any confidential bugs or issues to the Warp support team
  - name: Documentation
    url: https://docs.warp.dev/help/known-issues?q=
    about: Documentation for full telemetry table, known issues, troubleshooting, features, and more!
  - name: Discord
    url: https://discord.gg/warpdotdev
    about: Discuss what you want to see in a modern terminal, report bugs, and brainstorm features for Warp.
  - name: Warp Homepage
    url: https://www.warp.dev/
    about: Warps website.
  - name: Blog
    url: https://blog.warp.dev/
    about: See our blog.
  - name: Changelog
    url: https://docs.warp.dev/help/changelog
    about: See our changelog.
  - name: Licenses
    url: https://docs.warp.dev/help/licenses
    about: See the projects that we depend on and their open source licenses.
